{% set name = "opentelemetry-instrumentation-sqlite3" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-sqlite3-{{ version }}.tar.gz
  sha256: 0de0e6b0a7f2c77b2e0e34aa4781f0b42dd00e609f9d2cd81cd3060821ed1138

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - opentelemetry-instrumentation-dbapi ==0.26b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-test ==0.25b2
    # - opentelemetry-test-utils ==0.26b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sqlite3
  summary: OpenTelemetry SQLite3 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
